### ISSUE TITLE
Remove this linter? JSXHint is discontinued

### ISSUE THREAD

**Issue by iam4x** [AtomLinter/linter-jsxhint#17]
https://medium.com/@STRML/ending-jsxhint-1c09ed36cca9

**Comment by STRML** [comment]
JSXHint bugfixes will still be maintained into the future, but I recommend users use ESLint if they can. JSXHint will still stick around for some time due to ESLint incompatibilities, such as https://github.com/fxbois/web-mode/issues/473.

**Comment by jeffbski** [comment]
I believe we have figured out how to get eslint working with jsx files using web-mode in emacs. The details are in this comment: https://github.com/fxbois/web-mode/issues/473#issuecomment-87735443

I'll plan to create a blog article explaining in more detail.

**Comment by jeffbski** [comment]
Documented the emacs setup here: http://codewinds.com/blog/2015-04-02-emacs-flycheck-eslint-jsx.html

**Comment by Arcanemagus** [comment]
@imalitavakoli @jonathandelgado @ccorcos @hershmire @mende

As the base linter has been deprecated and will no longer be worked on, and this linter package has had no active development on it it seems that this package should be unpublished and removed from `apm`.

As you 5 are the only ones that have filed issues on it being broken since the Linter API update, are any of you interested in updating this and maintaining it or any other reason this shouldn't be removed?

**Comment by jonathandelgado** [comment]
@Arcanemagus  I moved over to eslint, +1 for unpublishing this.

**Comment by STRML** [comment]
:+1: won't hurt my feelings, it's not a great linter at all compared to eslint.

**Comment by iam4x** [comment]
Annnnnnd it's gone :100:

**Comment by steelbrain** [comment]
Closing as `linter-jsxhint` has been unpublished from APM
